student_count = 12

puts "The students of VILLANS academy"
puts "-------------"
puts "Dr Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratchet"
puts "Michael Corleon"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddie Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
puts "Baal"
print "Overall, we have #{student_count} great students"